"""Planner-facing decision validator: ground the planner like the workers.

The worker writes ``handoff.json`` and loops on ``check_handoff.py`` until it
exits 0 before handing back (``check_handoff.py``); the planner gets the SAME
discipline for its epoch JSON. It writes ``decision.json`` into its worktree CWD,
runs ``python3 check_decision.py decision.json``, and fixes every violation the
script prints until it exits 0. grindstone then reads the already-validated file
back as the disk contract, the core gate (``validate_decision``) re-runs as
defense in depth, and the planner stops burning blind re-asks on a schema it
guessed wrong (a real dogfood halt: a flattened, overlong epoch).

Unlike the worker validator, this one does NOT re-implement the schema walk: the
planner runs on the grindstone HOST, so the script simply re-execs the real core
gate. ``validate_decision`` is the single source of truth; ``write_validator``
drops a tiny stdlib wrapper that re-execs it through the grindstone interpreter
with the boundary's validation context baked in. The corpus-equivalence test
(``test_check_decision``) pins the script verdict to the core gate.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import cast

from grindstone.planner import (
    DEFAULT_LOCAL_MAX_TASK_FILES,
    DEFAULT_SENIOR_MAX_TASK_FILES,
    extract_decision_json,
    validate_decision,
)

#: The filename the wrapper is written as, and the command the planner re-runs.
#: Co-located with the generator so the boundary reuses both.
CHECK_SCRIPT_NAME = "check_decision.py"
CHECK_COMMAND = f"python3 {CHECK_SCRIPT_NAME} decision.json"
#: Where the planner writes its candidate decision, and the baked validation context.
DECISION_FILE = "decision.json"
CONTEXT_FILE = "decision_context.json"


def _run(decision_path: Path, context_path: Path) -> tuple[int, str]:
    """Validate ``decision_path`` against the core gate using the baked context.

    Returns ``(exit_code, message)``: ``(0, "OK …")`` when the decision conforms,
    else ``(1, "<violations>")`` with one human-readable reason per line, exactly
    the strings the core gate would feed the re-ask ladder.
    """

    try:
        text: str | None = decision_path.read_text(encoding="utf-8")
    except OSError as exc:
        return 1, f"cannot read {decision_path.name}: {exc}"
    try:
        raw = json.loads(context_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return 1, f"cannot read validation context: {exc}"
    if not isinstance(raw, dict):
        return 1, "validation context is not a JSON object"
    ctx = cast("dict[str, object]", raw)

    gate = validate_decision(
        extract_decision_json(text or ""),
        existing_log_keys=frozenset(cast("list[str]", ctx.get("existing_log_keys", []))),
        completed_phase_ids=frozenset(
            cast("list[str]", ctx.get("completed_phase_ids", []))
        ),
        skeleton_exists=bool(ctx.get("skeleton_exists", False)),
        phase_escalated=bool(ctx.get("phase_escalated", False)),
        failed_epoch_active=bool(ctx.get("failed_epoch_active", False)),
        has_senior=bool(ctx.get("has_senior", False)),
        local_max_task_files=int(
            cast("int", ctx.get("local_max_task_files", DEFAULT_LOCAL_MAX_TASK_FILES))
        ),
        senior_max_task_files=int(
            cast("int", ctx.get("senior_max_task_files", DEFAULT_SENIOR_MAX_TASK_FILES))
        ),
    )
    if gate.decision is not None:
        return 0, "OK: decision conforms to the epoch-decision schema."
    return 1, "\n".join(gate.errors)


def generate_check_script(*, grindstone_python: str, context_path: str) -> str:
    """Return the wrapper source the planner runs (pure, no I/O).

    A self-contained stdlib script that re-execs the real core gate through the
    grindstone interpreter, so the planner's local verdict is byte-identical to
    the core gate it will face. The interpreter path and the boundary's context
    file are baked in as literals; the body is invariant.
    """

    return (
        "# Generated by grindstone.check_decision for one planner boundary. DO NOT EDIT.\n"
        "# Re-execs the real grindstone decision gate so the planner self-corrects its\n"
        "# epoch JSON against the SAME validator the core applies after it hands back.\n"
        "import subprocess\n"
        "import sys\n"
        f"_GRINDSTONE_PYTHON = {grindstone_python!r}\n"
        f"_CONTEXT = {context_path!r}\n"
        "_TARGET = sys.argv[1] if len(sys.argv) > 1 else 'decision.json'\n"
        "sys.exit(\n"
        "    subprocess.run(\n"
        "        [_GRINDSTONE_PYTHON, '-m', 'grindstone.check_decision', _TARGET,\n"
        "         '--context', _CONTEXT]\n"
        "    ).returncode\n"
        ")\n"
    )


def write_validator(
    workdir: Path, *, context: dict[str, object], grindstone_python: str
) -> None:
    """Drop ``check_decision.py`` + ``decision_context.json`` into the planner CWD.

    Best-effort caller responsibility to ensure ``workdir`` exists; the boundary's
    worktree always does. The context is the exact keyword set ``validate_decision``
    needs (log keys, completed phases, position + size bounds for THIS call).
    """

    (workdir / CONTEXT_FILE).write_text(
        json.dumps(context, sort_keys=True, indent=2), encoding="utf-8"
    )
    (workdir / CHECK_SCRIPT_NAME).write_text(
        generate_check_script(
            grindstone_python=grindstone_python,
            context_path=str((workdir / CONTEXT_FILE).resolve()),
        ),
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="grindstone.check_decision")
    parser.add_argument("decision", type=Path, help="the candidate decision JSON file")
    parser.add_argument(
        "--context", type=Path, required=True, help="baked validation context JSON"
    )
    ns = parser.parse_args(argv)
    code, message = _run(ns.decision, ns.context)
    print(message)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
